services:
  # Backend
  - type: web
    name: url-to-pdf-backend
    env: docker
    rootDir: backend
    envVars:
      - key: PORT
        value: 10000

  # Frontend
  - type: static_site
    name: url-to-pdf-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://url-to-pdf-backend.onrender.com

