services:
  # Backend
  - type: web
    name: url-to-pdf-backend
    env: docker
    rootDir: backend
    envVars:
      - key: PORT
        value: 10000

  # Frontend
  - type: web
    name: url-to-pdf-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishDir: dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          name: url-to-pdf-backend
          type: web
          property: host
